Lab4-6/Hotel/Models/Room.cs
using Hotel.Models.Observer;
using Hotel.Models.State;

namespace Hotel.Models
{
    public class Room : IRoomObserver
    {
        public int ID;
        public string Type { get; set;}
        public double Price {get; set;} 
        public string Image { get; set;}
        public string Description { get; set;}
        public List<Furniture> Furniture { get; set; }
        public IRoomState State { get; set; }
        public string StateInfo { get; set; }
        public bool IsAvailable { get; set;}

        public List<string> AdditionalFeatures { get; set; }

        public void UpdateState(IRoomState newState)
        {
            State = newState;
        }

        public void ChangeState() {

            State.Handle(this);
        }

        public void AddFeatureToRoom(string feature)
        {
            AdditionalFeatures.Add(feature);
        }
    }
}

Lab4-6/Hotel/Controllers/FurnitureController.cs
using Hotel.Models.Builders;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using Hotel.Models.AbstractFactory;

namespace Hotel.Controllers
{
    public class FurnitureController : Controller
    {
        private readonly ILogger<FurnitureController> _logger;
        public FurnitureController(ILogger<FurnitureController> logger)
        {
            _logger = logger;
        }

        public Hotel.Models.Hotel hotel = Hotel.Models.Hotel.GetInstance();

        public IActionResult FurnitureInfo(string shop)
        {
            List<Furniture> model = new List<Furniture>();

            Furniture chair;
            Furniture table;
            Furniture sofa;
            Furniture bed;

            FurnitureFactory furnitureFactory = new EconomyFurnitureFactory();
             

            switch (shop)
            {
                case "economy":
                    furnitureFactory = new EconomyFurnitureFactory();
                    break;

                case "standard":
                    furnitureFactory = new StandardFurnitureFactory();
                    break;

                case "luxe":
                    furnitureFactory = new LuxeFurnitureFactory();
                    break;

                default:

                    break;
            }

            chair = furnitureFactory.CreateChair();
            table = furnitureFactory.CreateTable();
            sofa = furnitureFactory.CreateSofa();
            bed = furnitureFactory.CreateBed();

            model.Add(chair);
            model.Add(table);
            model.Add(sofa);
            model.Add(bed);

            return View("FurnitureInfo", model);
        }
    }
}

Lab4-6/Hotel/Controllers/RoomsController.cs
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Hotel.Models.Builders;
using Hotel.Models.Decorator;
using Hotel.Models.Strategy;
using Hotel.Models.State;

namespace Hotel.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ILogger<RoomsController> _logger;
        public RoomsController(ILogger<RoomsController> logger)
        {
            _logger = logger;
        }
        public Hotel.Models.Hotel hotel = Hotel.Models.Hotel.GetInstance();
        public IActionResult RoomsInfo(string viewMode)
        {
            ViewBag.ViewMode = viewMode;
             
            if(hotel.Rooms.Count == 0)
            {
                int idCounter = 1;

                var economyBuilder = new EconomyBuilder();
                var director = new BuilderDirector(economyBuilder);

                director.ConstructRoom();
                Room economyRoom1 = economyBuilder.GetRoom();
                economyRoom1.ID = idCounter++;
                Room economyRoom2 = economyBuilder.GetRoom();
                economyRoom2.ID = idCounter++;

                hotel.Rooms.Add(economyRoom1);
                hotel.Rooms.Add(economyRoom2);

                var standardBuilder = new StandardBuilder();
                director = new BuilderDirector(standardBuilder);

                director.ConstructRoom();
                Room standardRoom = standardBuilder.GetRoom();
                standardRoom.ID = idCounter++;

                hotel.Rooms.Add(standardRoom);

                var luxeBuilder = new LuxeBuilder();
                director = new BuilderDirector(luxeBuilder);

                director.ConstructRoom();
                Room luxeRoom = luxeBuilder.GetRoom();
                luxeRoom.ID = idCounter++;

                hotel.Rooms.Add(luxeRoom);

                foreach (var room in hotel.Rooms)
                {
                    hotel.AddRoomObserver(room);
                }

            }

            return View(hotel.Rooms);
        }
        public IActionResult EditRooms()
        {
            return View();
        }

        public IActionResult AddRoom(string roomType, bool goodView, bool wifi, bool breakfast)
        {
            int idCounter = hotel.Rooms.Count + 1; 

            IBuilder roomBuilder = null;
            switch (roomType.ToLower())
            {
                case "economy":
                    roomBuilder = new EconomyBuilder();
                    break;
                case "standard":
                    roomBuilder = new StandardBuilder();
                    break;
                case "luxe":
                    roomBuilder = new LuxeBuilder();
                    break;
                default:
                    return RedirectToAction("Error");
            }

            var director = new BuilderDirector(roomBuilder);

            director.ConstructRoom();
          
            Room newRoom = roomBuilder.GetRoom();
            newRoom.ID = idCounter;

            if(goodView == true)
            {
                var decorator = new GoodViewDecorator(newRoom);
                decorator.SetPrice();
                decorator.SetDescription();
            }
            if(wifi == true)
            {
                var decorator = new WiFiDecorator(newRoom);
                decorator.SetPrice();
                decorator.SetDescription();
            }
            if(breakfast == true)
            {
                var decorator = new BreakFastDecorator(newRoom);
                decorator.SetPrice();
                decorator.SetDescription();
            }

            hotel.Rooms.Add(newRoom);
            hotel.AddRoomObserver(newRoom);
            foreach (var feature in hotel.Features)
            {
                newRoom.AddFeatureToRoom(feature);
            }
            return View("RoomsInfo", hotel.Rooms);
        }
        public IActionResult SortRooms(string sortType)
        {
            RoomSortManager manager = new RoomSortManager(new SortByEconomyStandardLuxuryStrategy());

            switch (sortType.ToLower())
            {
                case "priceascending":
                    manager = new RoomSortManager(new SortByPriceAscendingStrategy());
                    break;
                case "pricedescending":
                    manager = new RoomSortManager(new SortByPriceDescendingStrategy());
                    break;
                case "typeluxurystandardeconomy":
                    manager = new RoomSortManager(new SortByLuxuryStandardEconomyStrategy());
                    break;
                case "typeeconomystandardluxury":
                    manager = new RoomSortManager(new SortByEconomyStandardLuxuryStrategy());
                    break;
                default:
                    return RedirectToAction("Error");
            }
            manager.SortRooms(hotel.Rooms);

            return View("RoomsInfo", hotel.Rooms);
        }

        public IActionResult ChangeState(string state, int roomID)
        {
            Room room = hotel.Rooms.FirstOrDefault(r => r.ID == roomID);

            if(room != null) {
                switch (state)
                {
                    case "repairing":
                        room.UpdateState(new RepairState());
                        room.ChangeState();
                        break;
                    case "cleaning":
                        room.UpdateState(new CleaningState());
                        room.ChangeState();
                        break;
                    default:
                        break;
                }
            }

            return View("RoomsInfo", hotel.Rooms);
        }
    }
}

Lab4-6/Hotel/Views/Rooms/EditRooms.cshtml
@{
    ViewData["Title"] = "Edit rooms";
}
<style>
    .add-room-price{
        margin-left: 60px;
    }

    .item {
        display: flex;
        align-items: center;
    }

        .item img {
            width: 50px; 
            height: auto; 
            margin-right: 10px; 
        }

    .details {
        flex-grow: 1; 
    }

        .details h4 {
            margin: 0;
        }
</style>

<script>

    function showFurniture() {
        var shopSelect = document.getElementById("shopSelect");
        var selectedShop = shopSelect.value;

        document.getElementById("furnitureList").style.display = "block";
        document.getElementById("economyFurniture").style.display = "none";
        document.getElementById("standardFurniture").style.display = "none";
        document.getElementById("luxeFurniture").style.display = "none";

        if (selectedShop === "economy") {
            document.getElementById("economyFurniture").style.display = "block";
        } else if (selectedShop === "standard") {
            document.getElementById("standardFurniture").style.display = "block";
        } else if (selectedShop === "luxe") {
            document.getElementById("luxeFurniture").style.display = "block";
        }
    }
</script>


@{

    Hotel hotel = Hotel.GetInstance();
}

<h4>Budget: @hotel.Budget</h4>
<h6>Buy new furniture</h6>
<form id="shopForm">
    <div class="form-group">
        <label for="shopSelect">Shop:</label>
        <select class="form-control" id="shopSelect" name="shopSelect">
            <option value="economy">Economy</option>
            <option value="standard">Standard</option>
            <option value="luxe">Luxe</option>
        </select>
    </div>
    <button type="button" class="btn btn-primary" onclick="showFurniture()">Select shop</button>
</form>

<div id="furnitureList" style="display: none;">
    <h6>Furniture:</h6>
    <div id="economyFurniture" style="display: none;">
        <ul>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Chair</h4>
                        <p>Price: 3000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                  
                    <div class="details">
                        <h4>Table</h4>
                        <p>Price: 3000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Sofa</h4>
                        <p>Price: 9900</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                   
                    <div class="details">
                        <h4>Bed</h4>
                        <p>Price: 4900</p>
                    </div>
                </div>
            </li>
        </ul>
        <a class="btn btn-success" asp-controller="Furniture" asp-action="FurnitureInfo" asp-route-shop="economy">Buy</a>
    </div>
    <div id="standardFurniture" style="display: none;">
        <ul>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Chair</h4>
                        <p>Price: 8000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                   
                    <div class="details">
                        <h4>Table</h4>
                        <p>Price: 7000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                   
                    <div class="details">
                        <h4>Sofa</h4>
                        <p>Price: 15000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Bed</h4>
                        <p>Price: 8900</p>
                    </div>
                </div>
            </li>
        </ul>
        <a class="btn btn-success" asp-controller="Furniture" asp-action="FurnitureInfo" asp-route-shop="standard">Buy</a>
    </div>
    <div id="luxeFurniture" style="display: none;">
        <ul>
            <li>
                <div class="item">
                   
                    <div class="details">
                        <h4>Chair</h4>
                        <p>Price: 12000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Table</h4>
                        <p>Price: 10000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Sofa</h4>
                        <p>Price: 17000</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="item">
                    
                    <div class="details">
                        <h4>Bed</h4>
                        <p>Price: 18000</p>
                    </div>
                </div>
            </li>
        </ul>
        <a class="btn btn-success" asp-controller="Furniture" asp-action="FurnitureInfo" asp-route-shop="luxe">Buy</a>
    </div>
</div>


<form id="addRoomForm" asp-controller="Rooms" asp-action="AddRoom">
    <div class="form-group mt-5">
        <label for="roomType">Room:</label>
        <select class="form-control" id="roomType" name="roomType">
            <option value="Economy">Economy</option>
            <option value="Standard">Standard</option>
            <option value="Luxe">Luxe</option>
        </select>
    </div>
    <div class="form-group mt-2">
        <label>Additional:</label><br>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="goodViewCheckbox" name="goodView" value = true>
            <label class="form-check-label" for="goodViewCheckbox">Good view</label>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="wifiCheckbox" name="wifi" value=true>
            <label class="form-check-label" for="wifiCheckbox">Wi-Fi</label>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="breakfastCheckbox" name="breakfast" value=true>
            <label class="form-check-label" for="breakfastCheckbox">Breakfast</label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Add room</button>
</form>

Lab4-6/Hotel/Views/Rooms/RoomsInfo.cshtml
@model List<Room>

@{
    ViewData["Title"] = "Rooms";
}
<style>
    .room-info {
        display: flex;
        align-items: center;
    }

    .room-info h2 {
    color:dimgray;
    }
    .room-info img {
        width: 250px;
        height: 250px;
        margin-right: 10px;
        margin-top: 40px;
    }

    .room-details {
        flex-grow: 1; 
    }

    .room-price {
        margin-left: auto;
        margin-right: 20px;
        font-size: 24px;
    }
    .room-id{
        margin-right: 20px;
        font-size: 18px;
    }
    .room-state{
        margin-right: 20px;
    }
    .mode{
        color:dimgray;
        font-size:20px;
    }
    .nav-link{
        color: dimgray;
        font-size: 20px;

    }

    .room-features{
        margin-right: 50px;
        color: darkgreen;
    }

</style>
@{
     Hotel hotel = Hotel.GetInstance();
}

<div class="container justify-content-between">

    <h1>Rooms</h1>
    <h4>Budget: @hotel.Budget</h4>
</div>

<div class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container justify-content-between">
        <ul class="navbar-nav">
            <li class="nav-item mr-3">
                <a class="mode nav-link" href="@Url.Action("RoomsInfo", "Rooms", new { viewMode = "list" })">List</a>
            </li>
            <li class="nav-item mr-3">
                <a class="mode nav-link" href="@Url.Action("RoomsInfo", "Rooms", new { viewMode = "table" })">Table</a>
            </li>
        </ul>
        <a class="nav-link" asp-controller="Rooms" asp-action="EditRooms">Editing rooms</a>
    </div>
</div>

<form asp-controller="Rooms" asp-action="SortRooms" class="form-inline">
    <label for="sortType" class="mr-2">Sort by:</label>
    <select name="sortType" id="sortType" class="form-control mr-2">
        <option value="" selected disabled>Choose an option</option>
        <option value="priceAscending">Price Ascending</option>
        <option value="priceDescending">Price Descending</option>
        <option value="typeLuxuryStandardEconomy">Type Luxury--Economy</option>
        <option value="typeEconomyStandardLuxury">Type Economy--Luxury</option>
    </select>
    <button type="submit" class="btn btn-primary">Sort</button>
</form>

@if ((string)ViewBag.ViewMode == "table")
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Description</th>
                <th>Features</th>
                <th>State</th>
                <th>Price</th>
                <th></th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var room in Model)
            {
                <tr>
                    <td>@room.ID</td>
                    <td>@room.Type</td>
                    <td>@room.Description</td>
                    <td>
                        @foreach (var feature in @room.AdditionalFeatures)
                     {
                            <p>@feature</p>
                     }
                    </td>
                    <td>@room.StateInfo</td>
                    <td>@room.Price</td>
                   <td>
                        <a class="btn btn-success" asp-controller="Rooms" asp-action="ChangeState" asp-route-state="cleaning" asp-route-roomID="@room.ID">Cleaning</a>
                        <a class="btn btn-success" asp-controller="Rooms" asp-action="ChangeState" asp-route-state="repairing" asp-route-roomID="@room.ID">Repairing</a>
                   </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    @foreach (var room in Model)
    {
        <div class="room-info">
            <div class="room-id">
                <p>ID: @room.ID</p>
            </div>
            <img src="@room.Image" alt="Room Image">
            <div class="room-details">
                <h2>@room.Type</h2>
                <p>@room.Description</p>
                <div class="room-features">
                    @foreach (var feature in @room.AdditionalFeatures)
                    {
                        <p>@feature</p>
                    }
                </div>
            </div>
         
            <div class="room-state">
                <p style="color:red">@room.StateInfo</p>
            </div>
            <div class="room-price ">
                <p>Price: @room.Price</p>
            </div>
            <div>
                <a class="btn btn-success" asp-controller="Rooms" asp-action="ChangeState" asp-route-state="cleaning" asp-route-roomID="@room.ID">Cleaning</a>
                <a class="btn btn-success" asp-controller="Rooms" asp-action="ChangeState" asp-route-state="repairing" asp-route-roomID="@room.ID">Repairing</a>
            </div>
        </div>
    }
}